// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 14.06.2024, 14:24:56
const configMerger = require("/Users/egorvilavin/Desktop/app_test/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/egorvilavin/Desktop/app_test/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/egorvilavin/Desktop/app_test/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/egorvilavin/Desktop/app_test/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/egorvilavin/Desktop/app_test/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/egorvilavin/Desktop/app_test/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/egorvilavin/Desktop/app_test/plugins/**/*.{js,ts,mjs}","/Users/egorvilavin/Desktop/app_test/composables/**/*.{js,ts,mjs}","/Users/egorvilavin/Desktop/app_test/utils/**/*.{js,ts,mjs}","/Users/egorvilavin/Desktop/app_test/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/egorvilavin/Desktop/app_test/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/egorvilavin/Desktop/app_test/app.config.{js,ts,mjs}"] }));

module.exports = config
