// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 21.06.2024, 14:12:44
const configMerger = require("/Users/egorvilavin/Desktop/Денис Орловский сайт/denis_nuxt/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/egorvilavin/Desktop/Денис Орловский сайт/denis_nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/egorvilavin/Desktop/Денис Орловский сайт/denis_nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/egorvilavin/Desktop/Денис Орловский сайт/denis_nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/egorvilavin/Desktop/Денис Орловский сайт/denis_nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/egorvilavin/Desktop/Денис Орловский сайт/denis_nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/egorvilavin/Desktop/Денис Орловский сайт/denis_nuxt/plugins/**/*.{js,ts,mjs}","/Users/egorvilavin/Desktop/Денис Орловский сайт/denis_nuxt/composables/**/*.{js,ts,mjs}","/Users/egorvilavin/Desktop/Денис Орловский сайт/denis_nuxt/utils/**/*.{js,ts,mjs}","/Users/egorvilavin/Desktop/Денис Орловский сайт/denis_nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/egorvilavin/Desktop/Денис Орловский сайт/denis_nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/egorvilavin/Desktop/Денис Орловский сайт/denis_nuxt/app.config.{js,ts,mjs}"] }));

module.exports = config
